### PR TITLE
Clean up the UI and fix issue with item use toggleing upgrade button

### PR DESCRIPTION
**Pull request by vanZeben**
Moves all the UI elements into the same line and clean up the visual names (No reason to use "Auto" in front of every single function, just redundant and takes up space), also combines SFX and Music into a single sound button...

Also the Item use was toggling the upgrade button

### CODE REVIEW

**Comment by ensingm2** [comment]
As of https://github.com/ensingm2/SteamMonsterGameScript/commit/7285f29f254df35a33aabe43887bb3ceccc0b041 , The slave script buttons take up the area after the sfx/music buttons. Adding these in as well clutters the bar, And I think it's a good idea to have the button groups separate. Closing this pull request, comment as needed.

**Comment by vanZeben** [comment]
I was going to say hold off on this one, commited this before I saw you move them up. Working on a better way, but d9b4045 could be pulled in regardless, pure empty space, and integrates the ugly quit button better

**Comment by ensingm2** [comment]
As far as pulling in d9b4045, it relies on 7d1d0d0. I can either update the master by hand, or if you want or you can revert 7d1d0d0 and I can merge in this request.

**Comment by vanZeben** [comment]
Im cleaning it up right now, give me a few minutes :D

**Comment by vanZeben** [comment]
God its been awhile for me with git... Let me clean this up and ill open a new one

**Comment by ensingm2** [comment]
I'm actually almost done fixing it up, no worries

**Comment by ensingm2** [comment]
See https://github.com/ensingm2/SteamMonsterGameScript/pull/61

**Pull request closed without merging**
