### PR TITLE
Vastly Upgrade the settings/options ui

### PR DESCRIPTION
**Pull request by vanZeben**
Overhauls the double options UI to sync it up and remove those butt ugly buttons, settings tab is also hidden by default until clicked on
Initial:
ss 2015-06-15 at 10 08 27
After Clicking
Results

### CODE REVIEW

**Comment by ensingm2** [comment]
Damn, that looks awesome!

**Comment by ensingm2** [comment]
Any chance you could also throw in a left-side pullout menu for stats, similar to settings, but displaying player DPS, crit chance, time to live, etc? most of those stats already exist around in the code if you ctrl-f for them, they'd just need to be updated.

Suggested in https://github.com/ensingm2/SteamMonsterGameScript/issues/96

**Comment by vanZeben** [comment]
Easy peasy, but you'll have to let me know what stats should be encorporated

**Comment by ensingm2** [comment]
Hmm, maybe the following to start?
- Player DPC - `g_Minigame.m_CurrentScene.m_rgPlayerTechTree.damage_per_click`
- Player DPS - `g_Minigame.m_CurrentScene.m_rgPlayerTechTree.damage_per_click * clicksPerSecond`
- Player Critrate `g_Minigame.m_CurrentScene.m_rgPlayerTechTree.crit_percentage`
- Crit Damage Multiplier  `g_Minigame.m_CurrentScene.m_rgPlayerTechTree.damage_multiplier_crit`
- Max Elemental Mutiplier `Math.max(g_Minigame.m_CurrentScene.damage_multiplier_air, ...........)`
- Max Elemental DPC `Math.max(g_Minigame.m_CurrentScene.damage_multiplier_air, ...........) * dpc`
- Max Elemental DPS `Math.max(g_Minigame.m_CurrentScene.damage_multiplier_air, ...........) * dps`
  - Boss Loot Drop Chance `g_Minigame.m_CurrentScene.m_rgPlayerTechTree.boss_loot_drop_percentage`

Dunno, anything else you think that should be added/removed?

**Pull request merged**
