### PR TITLE
Add refresh-stats button

### PR DESCRIPTION
**Pull request by kevin-abiera**
Instead of updating stats timely (doesn't seem to work on
Chrome+Tampermonkey), use a refresh button instead. And a little less
work on the CPU.

### CODE REVIEW

**Comment by vanZeben** [comment]
This updates every 10 seconds and shouldn't change much since its based off of your seconds per level which wont increment by much if you're 1000+ levels in (Levels it out and may change the expected level by only a few levels if any), hence why you may not be noticing it, but it does work

**Comment by ensingm2** [comment]
He was adding it because it doesn't seem the stats ever update on their own. I tried to run that branch and the button didn't seem to work either though.

**Comment by kevin-abiera** [comment]
@ensingm2 Try the button after passing few levels. The change isn't noticeable on higher levels.
@vanZeben Tried the latest on my Chrome+Tampermonkey. I really doesn't update. Just once, during the initial update. This is not a major issue though :smile:

**Comment by ensingm2** [comment]
Ah yeah, you're right. I'm gonna try to get it auto-updating rather than requiring user interaction, however.

**Comment by ensingm2** [comment]
Oh wow I'm dumb for missing it for so long. There was a mixup and somebody accidentally used setTimeout instead of setInterval. Gonna push a fix in a sec.

**Comment by ensingm2** [comment]
Fixed in https://github.com/ensingm2/SteamMonsterGameScript/commit/2f37752ffde1dfc90eed7f737b7ad31adf50dfb9

**Pull request closed without merging**
