### PR TITLE
Update automator.js

### PR DESCRIPTION
**Pull request by EnragedRabisu**
This actually tells how many active raining gold abilities are in place; So I propose checking which one is greater. Downside is this can still earn less gold if the boss doesn't have the most active raining gold abilities. If someone wants to add a check for a boss with active raining gold abilities, I believe that would be optimal.

### CODE REVIEW

**Comment by ensingm2** [comment]
This code has no effect, as aIsGold and bIsGold are both booleans. 

If you would like us to merge this in, please edit the function "laneHasAbility()" to return the count of that type of ability in lane.

**Comment by EnragedRabisu** [comment]
Here's the thing; It already does. The function it uses already gives the number of active abilities with that ID in the lane.

It's less relevant where I am now, but at the start, people were spamming Raining Gold on every lane, so the script would constantly hop to random lanes because the variables were different (Each lane had a different number of raining gold abilities active).

The function I used to check this is the same one used in the "laneHasAbility()" function (with the current lane pasted in where the "lane" variable would normally be):
g_Minigame.m_CurrentScene.m_rgLaneData[g_Minigame.CurrentScene().m_rgPlayerData.current_lane].abilities[17]

**Comment by ensingm2** [comment]
Relevant code lines:

var aIsGold = laneHasAbility(mobA.m_nLane, 17);
var bIsGold = laneHasAbility(mobB.m_nLane, 17);

function laneHasAbility(lane, abilityID) {
    return typeof(g_Minigame.m_CurrentScene.m_rgLaneData[lane].abilities[abilityID]) != 'undefined';
} // This returns a boolean

// Current version
if(aIsGold)

// Your version
if(aIsGold > bIsGold)

//Both have the same effect. true === (true > false)

**Comment by EnragedRabisu** [comment]
Apparently this change (laneHasAbility) was made after I forked. I'll tinker with the method and get back to you.

**Comment by EnragedRabisu** [comment]
I believe that should do it. Let me know if I've missed anything.

**Pull request merged**
